# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/nutanix/dataprotection/v4/error/error.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'com/nutanix/dataprotection/v4/error/error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.nutanix.common.v1.config import config_pb2 as com_dot_nutanix_dot_common_dot_v1_dot_config_dot_config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/com/nutanix/dataprotection/v4/error/error.proto\x12#com.nutanix.dataprotection.v4.error\x1a)com/nutanix/common/v1/config/config.proto\"\xbd\x02\n\nAppMessage\x12\x10\n\x07message\x18\xc9\x01 \x01(\t\x12W\n\x08severity\x18\xca\x01 \x01(\x0e\x32\x44.com.nutanix.common.v1.config.MessageSeverityMessage.MessageSeverity\x12\r\n\x04\x63ode\x18\xcb\x01 \x01(\t\x12\x0f\n\x06locale\x18\xcc\x01 \x01(\t\x12\x14\n\x0b\x65rror_group\x18\xcd\x01 \x01(\t\x12Y\n\rarguments_map\x18\xce\x01 \x03(\x0b\x32\x41.com.nutanix.dataprotection.v4.error.AppMessage.ArgumentsMapEntry\x1a\x33\n\x11\x41rgumentsMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"Y\n\x16\x41ppMessageArrayWrapper\x12?\n\x05value\x18\xe8\x07 \x03(\x0b\x32/.com.nutanix.dataprotection.v4.error.AppMessage\"j\n\x1cSchemaValidationErrorWrapper\x12J\n\x05value\x18\xe8\x07 \x01(\x0b\x32:.com.nutanix.dataprotection.v4.error.SchemaValidationError\"\xe6\x01\n\rErrorResponse\x12_\n\x17\x61pp_message_array_error\x18\xc9\x01 \x01(\x0b\x32;.com.nutanix.dataprotection.v4.error.AppMessageArrayWrapperH\x00\x12k\n\x1dschema_validation_error_error\x18\xca\x01 \x01(\x0b\x32\x41.com.nutanix.dataprotection.v4.error.SchemaValidationErrorWrapperH\x00\x42\x07\n\x05\x65rror\"\xc7\x01\n\x15SchemaValidationError\x12\x12\n\ttimestamp\x18\xc9\x01 \x01(\t\x12\x14\n\x0bstatus_code\x18\xca\x01 \x01(\x05\x12\x0e\n\x05\x65rror\x18\xcb\x01 \x01(\t\x12\r\n\x04path\x18\xcc\x01 \x01(\t\x12\x65\n\x19validation_error_messages\x18\xcd\x01 \x03(\x0b\x32\x41.com.nutanix.dataprotection.v4.error.SchemaValidationErrorMessage\"\\\n\x1cSchemaValidationErrorMessage\x12\x11\n\x08location\x18\xc9\x01 \x01(\t\x12\x10\n\x07message\x18\xca\x01 \x01(\t\x12\x17\n\x0e\x61ttribute_path\x18\xcb\x01 \x01(\tBL\n#com.nutanix.dataprotection.v4.errorP\x01Z#com/nutanix/dataprotection/v4/errorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.nutanix.dataprotection.v4.error.error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.nutanix.dataprotection.v4.errorP\001Z#com/nutanix/dataprotection/v4/error'
  _globals['_APPMESSAGE_ARGUMENTSMAPENTRY']._loaded_options = None
  _globals['_APPMESSAGE_ARGUMENTSMAPENTRY']._serialized_options = b'8\001'
  _globals['_APPMESSAGE']._serialized_start=132
  _globals['_APPMESSAGE']._serialized_end=449
  _globals['_APPMESSAGE_ARGUMENTSMAPENTRY']._serialized_start=398
  _globals['_APPMESSAGE_ARGUMENTSMAPENTRY']._serialized_end=449
  _globals['_APPMESSAGEARRAYWRAPPER']._serialized_start=451
  _globals['_APPMESSAGEARRAYWRAPPER']._serialized_end=540
  _globals['_SCHEMAVALIDATIONERRORWRAPPER']._serialized_start=542
  _globals['_SCHEMAVALIDATIONERRORWRAPPER']._serialized_end=648
  _globals['_ERRORRESPONSE']._serialized_start=651
  _globals['_ERRORRESPONSE']._serialized_end=881
  _globals['_SCHEMAVALIDATIONERROR']._serialized_start=884
  _globals['_SCHEMAVALIDATIONERROR']._serialized_end=1083
  _globals['_SCHEMAVALIDATIONERRORMESSAGE']._serialized_start=1085
  _globals['_SCHEMAVALIDATIONERRORMESSAGE']._serialized_end=1177
# @@protoc_insertion_point(module_scope)
