# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/nutanix/dataprotection/v4/api_version.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'com/nutanix/dataprotection/v4/api_version.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/com/nutanix/dataprotection/v4/api_version.proto\x12\x1d\x63om.nutanix.dataprotection.v4\x1a google/protobuf/descriptor.proto\"_\n\nApiVersion\x12\r\n\x05MAJOR\x18\x01 \x01(\t\x12\r\n\x05MINOR\x18\x02 \x01(\t\x12\x14\n\x0cRELEASE_TYPE\x18\x03 \x01(\t\x12\x1d\n\x15RELEASE_TYPE_REVISION\x18\x04 \x01(\t:e\n\x10ntnx_api_version\x12\x1f.google.protobuf.ServiceOptions\x18\xd0\x0f \x01(\x0b\x32).com.nutanix.dataprotection.v4.ApiVersionB@\n\x1d\x63om.nutanix.dataprotection.v4P\x01Z\x1d\x63om/nutanix/dataprotection/v4b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.nutanix.dataprotection.v4.api_version_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.nutanix.dataprotection.v4P\001Z\035com/nutanix/dataprotection/v4'
  _globals['_APIVERSION']._serialized_start=116
  _globals['_APIVERSION']._serialized_end=211
# @@protoc_insertion_point(module_scope)
