# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/nutanix/dataprotection/v4/content/VMRecoveryPointComputeChangedRegions_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'com/nutanix/dataprotection/v4/content/VMRecoveryPointComputeChangedRegions_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.nutanix.dataprotection.v4 import api_version_pb2 as com_dot_nutanix_dot_dataprotection_dot_v4_dot_api__version__pb2
from com.nutanix.dataprotection.v4 import http_method_options_pb2 as com_dot_nutanix_dot_dataprotection_dot_v4_dot_http__method__options__pb2
from com.nutanix.dataprotection.v4.content import content_pb2 as com_dot_nutanix_dot_dataprotection_dot_v4_dot_content_dot_content__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nXcom/nutanix/dataprotection/v4/content/VMRecoveryPointComputeChangedRegions_service.proto\x12%com.nutanix.dataprotection.v4.content\x1a/com/nutanix/dataprotection/v4/api_version.proto\x1a\x37\x63om/nutanix/dataprotection/v4/http_method_options.proto\x1a\x33\x63om/nutanix/dataprotection/v4/content/content.proto\"\xdd\x01\n\'VmRecoveryPointComputeChangedRegionsArg\x12\x1e\n\x15recovery_point_ext_id\x18\xd1\x0f \x01(\t\x12!\n\x18vm_recovery_point_ext_id\x18\xd2\x0f \x01(\t\x12\x0f\n\x06\x65xt_id\x18\xd3\x0f \x01(\t\x12^\n\x04\x62ody\x18\xd4\x0f \x01(\x0b\x32O.com.nutanix.dataprotection.v4.content.VmRecoveryPointChangedRegionsComputeSpec\"\x99\x02\n\'VmRecoveryPointComputeChangedRegionsRet\x12L\n\x07\x63ontent\x18\xe7\x07 \x01(\x0b\x32:.com.nutanix.dataprotection.v4.content.ChangedRegionsModel\x12o\n\x08reserved\x18\xe8\x07 \x03(\x0b\x32\\.com.nutanix.dataprotection.v4.content.VmRecoveryPointComputeChangedRegionsRet.ReservedEntry\x1a/\n\rReservedEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xba\x03\n+VMRecoveryPointComputeChangedRegionsService\x12\xf9\x02\n$vmRecoveryPointComputeChangedRegions\x12N.com.nutanix.dataprotection.v4.content.VmRecoveryPointComputeChangedRegionsArg\x1aN.com.nutanix.dataprotection.v4.content.VmRecoveryPointComputeChangedRegionsRet\"\xae\x01\xc2>\xaa\x01\n\xa7\x01/dataprotection/v4/content/recovery-points/{recoveryPointExtId}/vm-recovery-points/{vmRecoveryPointExtId}/disk-recovery-points/{extId}/$actions/compute-changed-regions0\x01\x1a\x0f\x82}\x0c\n\x01\x34\x12\x01\x30\x1a\x01\x61\"\x01\x31\x42P\n%com.nutanix.dataprotection.v4.contentP\x01Z%com/nutanix/dataprotection/v4/contentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.nutanix.dataprotection.v4.content.VMRecoveryPointComputeChangedRegions_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.nutanix.dataprotection.v4.contentP\001Z%com/nutanix/dataprotection/v4/content'
  _globals['_VMRECOVERYPOINTCOMPUTECHANGEDREGIONSRET_RESERVEDENTRY']._loaded_options = None
  _globals['_VMRECOVERYPOINTCOMPUTECHANGEDREGIONSRET_RESERVEDENTRY']._serialized_options = b'8\001'
  _globals['_VMRECOVERYPOINTCOMPUTECHANGEDREGIONSSERVICE']._loaded_options = None
  _globals['_VMRECOVERYPOINTCOMPUTECHANGEDREGIONSSERVICE']._serialized_options = b'\202}\014\n\0014\022\0010\032\001a\"\0011'
  _globals['_VMRECOVERYPOINTCOMPUTECHANGEDREGIONSSERVICE'].methods_by_name['vmRecoveryPointComputeChangedRegions']._loaded_options = None
  _globals['_VMRECOVERYPOINTCOMPUTECHANGEDREGIONSSERVICE'].methods_by_name['vmRecoveryPointComputeChangedRegions']._serialized_options = b'\302>\252\001\n\247\001/dataprotection/v4/content/recovery-points/{recoveryPointExtId}/vm-recovery-points/{vmRecoveryPointExtId}/disk-recovery-points/{extId}/$actions/compute-changed-regions'
  _globals['_VMRECOVERYPOINTCOMPUTECHANGEDREGIONSARG']._serialized_start=291
  _globals['_VMRECOVERYPOINTCOMPUTECHANGEDREGIONSARG']._serialized_end=512
  _globals['_VMRECOVERYPOINTCOMPUTECHANGEDREGIONSRET']._serialized_start=515
  _globals['_VMRECOVERYPOINTCOMPUTECHANGEDREGIONSRET']._serialized_end=796
  _globals['_VMRECOVERYPOINTCOMPUTECHANGEDREGIONSRET_RESERVEDENTRY']._serialized_start=749
  _globals['_VMRECOVERYPOINTCOMPUTECHANGEDREGIONSRET_RESERVEDENTRY']._serialized_end=796
  _globals['_VMRECOVERYPOINTCOMPUTECHANGEDREGIONSSERVICE']._serialized_start=799
  _globals['_VMRECOVERYPOINTCOMPUTECHANGEDREGIONSSERVICE']._serialized_end=1241
# @@protoc_insertion_point(module_scope)
